use std::{any::Any, fmt::Debug, marker::PhantomData, rc::Rc};

use nestix_macros::{callback, computed};
use nestix_signal::{Shared, Signal};

/// Trait implemented by prop types that have a generated builder.
pub trait HasBuilder {
    /// The generated builder type.
    type Builder;
}

#[doc(hidden)]
/// Helper trait used by generated prop builders for nested prop values.
pub trait IntoRawValue<T> {
    #[doc(hidden)]
    fn into_raw_value(self) -> T;
}

impl<T> IntoRawValue<T> for T {
    #[inline]
    fn into_raw_value(self) -> T {
        self
    }
}

#[allow(private_bounds)]
/// Type-erased component props.
pub trait Props: Any {
    /// Formats props for debug output.
    fn debug_fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Props(..)")
    }

    /// Returns structured property metadata when inspector support was generated.
    #[cfg(feature = "inspector")]
    fn as_inspectable(&self) -> Option<&dyn InspectableProps> {
        None
    }
}

/// Whether an inspected property is plain, reactive, raw, or nested.
#[cfg(feature = "inspector")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InspectPropSource {
    Plain,
    Reactive,
    Raw,
    Nested,
}

/// Display-oriented value produced by property inspection.
#[cfg(feature = "inspector")]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InspectValue {
    Empty,
    Bool(bool),
    Number(String),
    Text(String),
    Callback,
    Element(crate::ElementId),
    Layout(usize),
    Display(String),
    Opaque(&'static str),
}

#[cfg(feature = "inspector")]
impl InspectValue {
    /// Formats this value for a compact inspector row.
    pub fn summary(&self) -> String {
        match self {
            Self::Empty => "None".to_string(),
            Self::Bool(value) => value.to_string(),
            Self::Number(value) => value.clone(),
            Self::Text(value) => format!("{value:?}"),
            Self::Callback => "<callback>".to_string(),
            Self::Element(id) => format!("<element #{}>", id.get()),
            Self::Layout(0) => "<empty layout>".to_string(),
            Self::Layout(1) => "<1 element>".to_string(),
            Self::Layout(count) => format!("<{count} elements>"),
            Self::Display(value) => value.clone(),
            Self::Opaque(type_name) => format!("<{type_name}>"),
        }
    }
}

/// One generated property entry exposed to component inspectors.
#[cfg(feature = "inspector")]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InspectProp {
    pub name: &'static str,
    pub type_name: &'static str,
    pub source: InspectPropSource,
    pub value: InspectValue,
    pub children: Vec<InspectProp>,
}

#[cfg(feature = "inspector")]
impl InspectProp {
    #[doc(hidden)]
    pub fn raw(name: &'static str, type_name: &'static str) -> Self {
        Self {
            name,
            type_name,
            source: InspectPropSource::Raw,
            value: inspect_opaque_type(type_name),
            children: Vec::new(),
        }
    }

    #[doc(hidden)]
    pub fn nested(name: &'static str, type_name: &'static str, children: Vec<InspectProp>) -> Self {
        Self {
            name,
            type_name,
            source: InspectPropSource::Nested,
            value: InspectValue::Opaque(type_name),
            children,
        }
    }
}

/// Structured property metadata generated by `#[props]`.
#[cfg(feature = "inspector")]
pub trait InspectableProps {
    fn inspect_props(&self) -> Vec<InspectProp>;
}

/// Converts an application-defined value into an inspector representation.
#[cfg(feature = "inspector")]
pub trait InspectableValue {
    fn inspect_value(&self) -> InspectValue;
}

#[cfg(feature = "inspector")]
macro_rules! inspect_number {
    ($($ty:ty),+ $(,)?) => {
        $(impl InspectableValue for $ty {
            fn inspect_value(&self) -> InspectValue {
                InspectValue::Number(self.to_string())
            }
        })+
    };
}

#[cfg(feature = "inspector")]
inspect_number!(
    u8, u16, u32, u64, u128, usize, i8, i16, i32, i64, i128, isize, f32, f64
);

#[cfg(feature = "inspector")]
impl InspectableValue for bool {
    fn inspect_value(&self) -> InspectValue {
        InspectValue::Bool(*self)
    }
}

#[cfg(feature = "inspector")]
impl InspectableValue for String {
    fn inspect_value(&self) -> InspectValue {
        InspectValue::Text(self.clone())
    }
}

#[cfg(feature = "inspector")]
impl InspectableValue for &'static str {
    fn inspect_value(&self) -> InspectValue {
        InspectValue::Text((*self).to_string())
    }
}

#[cfg(feature = "inspector")]
impl<T: InspectableValue> InspectableValue for Option<T> {
    fn inspect_value(&self) -> InspectValue {
        self.as_ref()
            .map(InspectableValue::inspect_value)
            .unwrap_or(InspectValue::Empty)
    }
}

#[cfg(feature = "inspector")]
impl<T> InspectableValue for Vec<T> {
    fn inspect_value(&self) -> InspectValue {
        InspectValue::Display(format!("<{} items>", self.len()))
    }
}

#[cfg(feature = "inspector")]
impl<T: ?Sized + 'static> InspectableValue for Rc<T> {
    fn inspect_value(&self) -> InspectValue {
        inspect_opaque_type(std::any::type_name::<T>())
    }
}

#[cfg(feature = "inspector")]
impl<T: ?Sized + 'static> InspectableValue for Shared<T> {
    fn inspect_value(&self) -> InspectValue {
        inspect_opaque_type(std::any::type_name::<T>())
    }
}

#[cfg(feature = "inspector")]
impl InspectableValue for crate::Element {
    fn inspect_value(&self) -> InspectValue {
        InspectValue::Element(self.id())
    }
}

#[cfg(feature = "inspector")]
impl InspectableValue for crate::Layout {
    fn inspect_value(&self) -> InspectValue {
        InspectValue::Layout(self.len())
    }
}

#[cfg(feature = "inspector")]
fn inspect_opaque_type(type_name: &'static str) -> InspectValue {
    if type_name.contains("dyn core::ops::function::Fn")
        || type_name.contains("dyn std::ops::function::Fn")
        || type_name.contains("dyn Fn")
    {
        InspectValue::Callback
    } else {
        InspectValue::Opaque(type_name)
    }
}

#[cfg(feature = "inspector")]
fn inspect_any<T: 'static>(value: &T) -> InspectValue {
    let any = value as &dyn Any;
    macro_rules! number {
        ($($ty:ty),+ $(,)?) => {
            $(if let Some(value) = any.downcast_ref::<$ty>() {
                return InspectValue::Number(value.to_string());
            })+
        };
    }
    number!(
        u8, u16, u32, u64, u128, usize, i8, i16, i32, i64, i128, isize, f32, f64
    );

    if let Some(value) = any.downcast_ref::<bool>() {
        return InspectValue::Bool(*value);
    }
    if let Some(value) = any.downcast_ref::<String>() {
        return InspectValue::Text(value.clone());
    }
    if let Some(value) = any.downcast_ref::<&'static str>() {
        return InspectValue::Text((*value).to_string());
    }
    if let Some(value) = any.downcast_ref::<Option<String>>() {
        return value
            .clone()
            .map(InspectValue::Text)
            .unwrap_or(InspectValue::Empty);
    }
    if let Some(value) = any.downcast_ref::<Option<bool>>() {
        return value.map(InspectValue::Bool).unwrap_or(InspectValue::Empty);
    }
    if let Some(value) = any.downcast_ref::<crate::Element>() {
        return InspectValue::Element(value.id());
    }
    if let Some(value) = any.downcast_ref::<Option<crate::Element>>() {
        return value
            .as_ref()
            .map(|element| InspectValue::Element(element.id()))
            .unwrap_or(InspectValue::Empty);
    }
    if let Some(value) = any.downcast_ref::<crate::Layout>() {
        return InspectValue::Layout(value.len());
    }

    inspect_opaque_type(std::any::type_name::<T>())
}

impl dyn Props {
    /// Returns these props as [`Any`] for downcasting.
    pub fn as_any(&self) -> &dyn Any {
        self
    }

    /// Attempts to downcast these props to `T`.
    pub fn downcast_ref<T: 'static>(&self) -> Option<&T> {
        self.as_any().downcast_ref::<T>()
    }
}

impl Debug for dyn Props {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.debug_fmt(f)
    }
}

impl Props for () {
    fn debug_fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "()")
    }
}

#[derive(Debug)]
enum PropValueInner<T> {
    Plain(Rc<T>),
    Signal(Shared<dyn Fn() -> T>),
}

impl<T> PartialEq for PropValueInner<T> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Plain(l0), Self::Plain(r0)) => Rc::ptr_eq(l0, r0),
            (Self::Signal(l0), Self::Signal(r0)) => l0 == r0,
            _ => false,
        }
    }
}

impl<T> Eq for PropValueInner<T> {}

/// A prop value that can be either plain data or a reactive signal.
#[derive(Debug)]
pub struct PropValue<T> {
    inner: PropValueInner<T>,
}

impl<T> PropValue<T> {
    /// Creates a prop value from plain, non-reactive data.
    pub fn from_plain(value: T) -> Self {
        Self {
            inner: PropValueInner::Plain(Rc::new(value)),
        }
    }

    /// Creates a prop value from a signal.
    pub fn from_signal<U: Into<T>, S: Signal<Output = U> + 'static>(signal: S) -> Self {
        Self {
            inner: PropValueInner::Signal(callback!(move || { signal.get().into() })),
        }
    }

    pub fn into_plain(self) -> Option<T> {
        match self.inner {
            PropValueInner::Plain(value) => Rc::try_unwrap(value).ok(),
            PropValueInner::Signal(_) => None,
        }
    }
}

#[cfg(feature = "inspector")]
impl<T: 'static> PropValue<T> {
    #[doc(hidden)]
    pub fn inspect_prop(&self, name: &'static str, type_name: &'static str) -> InspectProp {
        self.inspect_prop_with(name, type_name, inspect_any)
    }

    #[doc(hidden)]
    pub fn inspect_prop_with(
        &self,
        name: &'static str,
        type_name: &'static str,
        inspect: impl Fn(&T) -> InspectValue,
    ) -> InspectProp {
        let (source, value) = match &self.inner {
            PropValueInner::Plain(value) => (InspectPropSource::Plain, inspect(value.as_ref())),
            PropValueInner::Signal(signal) => (
                InspectPropSource::Reactive,
                nestix_signal::untrack(|| {
                    let value = signal();
                    inspect(&value)
                }),
            ),
        };
        InspectProp {
            name,
            type_name,
            source,
            value,
            children: Vec::new(),
        }
    }
}

impl<T: 'static> PropValue<T> {
    pub fn map<U: Clone + 'static>(self, f: impl Fn(&T) -> U + 'static) -> PropValue<U> {
        match self.inner {
            PropValueInner::Plain(plain) => PropValue::from_plain(f(&plain)),
            PropValueInner::Signal(shared) => PropValue::from_signal(computed!([] || f(&shared()))),
        }
    }
}

impl<T> IntoRawValue<T> for PropValue<T> {
    #[inline]
    fn into_raw_value(self) -> T {
        self.into_plain()
            .expect("raw props cannot be built from a shared or signal-backed PropValue")
    }
}

impl<T: Clone> PropValue<T> {
    /// Reads the current prop value.
    pub fn get(&self) -> T {
        match &self.inner {
            PropValueInner::Plain(value) => (**value).clone(),
            PropValueInner::Signal(signal) => signal(),
        }
    }
}

impl<T> Clone for PropValue<T> {
    fn clone(&self) -> Self {
        match &self.inner {
            PropValueInner::Plain(value) => Self {
                inner: PropValueInner::Plain(value.clone()),
            },
            PropValueInner::Signal(signal) => Self {
                inner: PropValueInner::Signal(signal.clone()),
            },
        }
    }
}

impl<T> PartialEq for PropValue<T> {
    fn eq(&self, other: &Self) -> bool {
        self.inner == other.inner
    }
}

impl<T> Eq for PropValue<T> {}

#[doc(hidden)]
/// Tag used by generated prop builders for plain values.
pub struct PlainTag<T>(PhantomData<T>);

impl<T> PlainTag<T> {
    /// Converts a plain value into a [`PropValue`].
    #[inline]
    pub fn new(self, value: impl Into<T>) -> PropValue<T> {
        PropValue::from_plain(value.into())
    }
}

#[doc(hidden)]
/// Helper trait used by generated prop builders for plain values.
pub trait PlainKind<T> {
    #[inline]
    fn prop_value_tag(&self) -> PlainTag<T> {
        PlainTag(PhantomData)
    }
}

impl<T, I: Into<T>> PlainKind<T> for &I {}

#[doc(hidden)]
/// Tag used by generated prop builders for signal values.
pub struct SignalTag<T>(PhantomData<T>);

impl<T> SignalTag<T> {
    /// Converts a signal into a [`PropValue`].
    #[inline]
    pub fn new<U: Into<T>, S: Signal<Output = U> + 'static>(self, value: S) -> PropValue<T> {
        PropValue::from_signal(value)
    }
}

#[doc(hidden)]
/// Helper trait used by generated prop builders for signal values.
pub trait SignalKind<T> {
    #[inline]
    fn prop_value_tag(&self) -> SignalTag<T> {
        SignalTag(PhantomData)
    }
}

impl<T, S> SignalKind<T> for S
where
    S: Signal,
    S::Output: Into<T>,
{
}

#[doc(hidden)]
/// Tag used by generated prop builders for existing [`PropValue`] values.
pub struct PropValueTag<T>(PhantomData<T>);

impl<T> PropValueTag<T> {
    /// Returns an existing [`PropValue`] unchanged.
    #[inline]
    pub fn new(self, value: PropValue<T>) -> PropValue<T> {
        value
    }
}

impl<T> PropValue<T> {
    #[doc(hidden)]
    #[inline]
    pub fn prop_value_tag(&self) -> PropValueTag<T> {
        PropValueTag(PhantomData)
    }
}
