//! Procedural macros for Nestix applications.
//!
//! Most users import these through `nestix` rather than depending on
//! `nestix-macros` directly. The macros here cover the three pieces of syntax
//! Nestix adds on top of regular Rust:
//!
//! - `#[component]` turns a function into a Nestix component type.
//! - `#[props]` turns a named-field struct into a prop container and builder.
//! - `layout!`, `callback!`, `computed!`, and friends keep component bodies
//!   compact while still expanding to normal runtime APIs.
//!
//! ```ignore
//! use nestix::{Element, callback, component, create_state, layout};
//!
//! #[component]
//! fn Counter() -> Element {
//!     let count = create_state(0);
//!
//!     layout! {
//!         Button(
//!             .on_click = callback!([count] || count.mutate(|value| *value += 1)),
//!         ) {
//!             Text("Click")
//!         }
//!     }
//! }
//! ```

use proc_macro::TokenStream;

mod build_props;
mod callback;
mod clone_var;
mod closure;
mod component;
mod layout;
mod prop_value;
mod props;
mod signals;
mod util;

/// Builds a closure after cloning the requested captures.
///
/// The capture list is optional. When it is present and the closure is not
/// already `move`, the macro inserts `move` so the cloned bindings are captured
/// by value.
///
/// ```ignore
/// let count = create_state(0);
/// let handler = closure!([count] || count.set(count.get() + 1));
///
/// let named = closure!([label: props.label] || label.get());
/// ```
#[proc_macro]
pub fn closure(input: TokenStream) -> TokenStream {
    closure::closure(input)
}

/// Builds a shared callback from a closure.
///
/// This is a convenience wrapper around [`closure!`] that returns
/// `nestix::Shared<dyn Fn(...) -> _>`.
///
/// ```ignore
/// Button(
///     .on_click = callback!([count] || count.mutate(|value| *value += 1)),
/// )
///
/// let remove = callback!([items] |key: &str| {
///     items.mutate(|items| {
///         items.shift_remove(key);
///     });
/// });
/// ```
#[proc_macro]
pub fn callback(input: TokenStream) -> TokenStream {
    callback::callback(input)
}

/// Derives Nestix prop behavior and a typed builder for a named-field struct.
///
/// Every field becomes a `PropValue<T>` unless it uses
/// `#[props(extends(TraitName, WrapperTraitName))]`. `Option<T>` fields are
/// defaulted automatically; other fields must be set by the generated builder
/// unless marked with `#[props(default)]` or `#[props(start)]`.
///
/// ```ignore
/// #[props]
/// struct ButtonProps {
///     #[props(default = "button".to_string())]
///     class: String,
///     disabled: bool,
///     on_click: Shared<dyn Fn()>,
/// }
///
/// let props = build_props!(ButtonProps(
///     .disabled = false,
///     .on_click = callback!(|| ()),
/// ));
/// ```
#[proc_macro_attribute]
pub fn props(attr: TokenStream, input: TokenStream) -> TokenStream {
    props::props(attr, input)
}

/// Converts a plain value, signal, or existing `PropValue` into a `PropValue`.
///
/// ```ignore
/// let plain = prop_value!("Hello".to_string());
/// let reactive = prop_value!(computed!([count] || format!("{count:?}")));
/// ```
#[proc_macro]
pub fn prop_value(input: TokenStream) -> TokenStream {
    prop_value::prop_value(input)
}

/// Builds a prop struct by driving the builder generated by [`props`].
///
/// Positional arguments fill `#[props(start)]` fields. Named arguments use the
/// `.field = value` syntax and are converted through [`prop_value!`].
///
/// ```ignore
/// let props = build_props!(InputProps(
///     input_value.clone(),
///     .on_value_change = callback!(|value| log::info!("{value}")),
/// ));
/// ```
#[proc_macro]
pub fn build_props(input: TokenStream) -> TokenStream {
    build_props::build_props(input)
}

/// Creates Nestix elements with component-oriented layout syntax.
///
/// The macro accepts elements, expression splices, `if`/`else` branches, and
/// signal-backed `for` loops.
///
/// ```ignore
/// layout! {
///     Div(.class = "todo-list".to_string()) {
///         for item in items.clone() where key = |item| item.0.clone() {
///             TodoListItem(.data = item)
///         }
///     }
/// }
/// ```
#[proc_macro]
pub fn layout(input: TokenStream) -> TokenStream {
    layout::layout(input)
}

/// Turns a function into a type that implements `nestix::Component`.
///
/// Component functions may accept no arguments, `&Props`, or `&Props` plus the
/// mounted `&Element`.
///
/// ```ignore
/// #[component]
/// fn TodoListItem(props: &TodoListItemProps) -> Element {
///     layout! {
///         Div {
///             Text(props.label.clone())
///         }
///     }
/// }
/// ```
#[proc_macro_attribute]
pub fn component(attr: TokenStream, input: TokenStream) -> TokenStream {
    component::component(attr, input)
}

/// Creates a reactive computed signal from closure syntax.
///
/// This wraps the runtime `nestix::computed` function after applying
/// [`closure!`] capture handling.
///
/// ```ignore
/// Text(computed!([count] || format!("Count: {}", count.get())))
/// ```
#[proc_macro]
pub fn computed(input: TokenStream) -> TokenStream {
    signals::computed(input)
}

/// Registers an effect from closure syntax.
///
/// This wraps the runtime `nestix::effect` function after applying [`closure!`]
/// capture handling.
///
/// ```ignore
/// effect!([element] || log::debug!("mounted {:?}", element.handle()));
/// ```
#[proc_macro]
pub fn effect(input: TokenStream) -> TokenStream {
    signals::effect(input)
}

/// Registers an element-scoped effect from closure syntax.
///
/// This wraps the runtime `nestix::scoped_effect` function after applying
/// [`closure!`] capture handling. The effect is automatically canceled when the
/// provided element unmounts.
///
/// ```ignore
/// scoped_effect!(element, [props.value] || sync_host(value.get()));
/// ```
#[proc_macro]
pub fn scoped_effect(input: TokenStream) -> TokenStream {
    signals::scoped_effect(input)
}
